name: hello

on:
  push:

jobs:
  trabajo1: 
    runs-on: ubuntu-latest

    steps:
      # 1) Clona tu repo
      - uses: actions/checkout@v3

      # 2) Instala dependencias de forma limpia
      - name: Instalar dependencias
        run: npm ci

      # 3) Escanea vulnerabilidades de alta severidad y falla si las hay
      - name: Escanear vulnerabilidades
        run: npm audit --audit-level=high

      # Tus pasos originales
      - name: Echo terminal
        run: echo Hello, world!
        
      - name: Di la fecha Hoy
        run: date