name: hello

on:
  push:

jobs:
  trabajo1: 
    runs-on: ubuntu-latest

    steps:
      # 1) Clona tu repo
      - uses: actions/checkout@v3

      # 2) Instala dependencias
      - name: Instalar dependencias
        run: npm ci

      # 3) Escanea vulnerabilidades de alta severidad y falla si las hay
      - name: Escanear vulnerabilidades
        run: npm audit --audit-level=high

      # 4) Instala Node.js (para tu backend)
      - name: Usar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 5) Instala sonar-scanner
      - name: Instalar sonar-scanner
        run: npm install -g sonar-scanner

      # 6) Ejecuta análisis en SonarCloud
      - name: Ejecutar análisis SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          npx sonar-scanner \
            -Dsonar.organization=eduauti \
            -Dsonar.projectKey=eduauti_veterinaria-backend \
            -Dsonar.sources=. \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.token=$SONAR_TOKEN

      # Tus pasos originales
      - name: Echo terminal
        run: echo Hello, world!
        
      - name: Di la fecha Hoy
        run: date
